// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIEEj9-IFKuzO4nWqxP9LE3KBH55IPlMw',
    appId: '1:1002644291978:web:a64fd7a47aa268da6bc873',
    messagingSenderId: '1002644291978',
    projectId: 'notes-app-fdec2',
    authDomain: 'notes-app-fdec2.firebaseapp.com',
    storageBucket: 'notes-app-fdec2.appspot.com',
    measurementId: 'G-3QJWMK007M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2yLb2SfHK3wl_BfhjfxLwkh-m6duA5HQ',
    appId: '1:1002644291978:android:4fe3e21a82d911766bc873',
    messagingSenderId: '1002644291978',
    projectId: 'notes-app-fdec2',
    storageBucket: 'notes-app-fdec2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmmvzUIKMf5BWTklH1-ZUqR1ak7m0OCv4',
    appId: '1:1002644291978:ios:ca2ef0d5c39ade216bc873',
    messagingSenderId: '1002644291978',
    projectId: 'notes-app-fdec2',
    storageBucket: 'notes-app-fdec2.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmmvzUIKMf5BWTklH1-ZUqR1ak7m0OCv4',
    appId: '1:1002644291978:ios:bf8931a40bf1b5436bc873',
    messagingSenderId: '1002644291978',
    projectId: 'notes-app-fdec2',
    storageBucket: 'notes-app-fdec2.appspot.com',
    iosBundleId: 'com.example.notesApp.RunnerTests',
  );
}
